<!DOCTYPE html>
<html lang="en" style="height: 100%;width: 100%;overflow-x: hidden">
<head>
    <meta charset="UTF-8">
    <title>服务器瞌睡了</title>
</head>
<style>
    * {
        font-size: 3rem;
        margin: 0;
        padding: 0
    }

    div {
        position: absolute;
        margin: auto;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        width: 15rem;
        height: 5rem;
        line-height: 5rem;
    }
</style>
<body style="height: 100%;width: 100%;">
<div>错误提示页</div>
</body>
</html>