<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Demo index page</title>
    <link rel="shortcut icon" href="/static/common/favicon.ico">
    <link rel="stylesheet" href="/static/common/css/pc-rest.css" type="text/css">
    <script src="/static/common/js/jquery-2.2.4.min.js"></script>
    <script src="/static/common/js/main.min.js"></script>
</head>
<body>
<h1>这是layout2.phtml</h1>
<?php require $this->_content; ?>
</body>
</html>